# 4.3: Notebook-Introduction to DataFrames

In this workbook, we introduce a popular Python library called Pandas that makes loading and saving data in different formats trivial. It's also very powerful for data manipulation, and thus selection.

We'll start with an example with the data in Python, we'll then look at loading and saving various common formats you're likely to encounter.

To use Pandas, we need to import it. By convention, Pandas is referred to by the abbreviation ``pd`` -- this isn't required, but it's very common.

In [3]:
import pandas as pd

## Pandas DataFrames

In Pandas, data are stored in a structure it calls a DataFrame. 
Conceptually, you can think of it as a table, with column headings and numbered rows, although DataFrames also function like databases.

DataFrame is a class in Python, so we create a DataFrame object by calling the constructor.
We'll use a few books for our data.
``df`` is a common variable name for a DataFrame.

In [3]:
df = pd.DataFrame({
    "title": ["Tangled Web",
              "Close Up",
              "Foundations",
              "Professional Secrets",
              "5 Times 5"],
    "author": ["Eric Mead",
               "David Stone",
               "Eberhard Riese",
               "Geoffrey Durham",
               "Richard Kaufman"],
    "price": [40, 23.1, 70, 295, 34.65]
})

df

                  title           author   price
0           Tangled Web        Eric Mead   40.00
1              Close Up      David Stone   23.10
2           Foundations   Eberhard Riese   70.00
3  Professional Secrets  Geoffrey Durham  295.00
4             5 Times 5  Richard Kaufman   34.65

You can clearly see the table-like structure above.
What looks like a column is actually a `Series` in `Pandas`.
The column names are taken from the dictionary that was passed into the constructor function.
Notice that row numbers have been added automatically and start from 0. 
This is the index.
It's possible to specify different row labels when constructing the DataFrame by passing in a value for the optional parameter ``index``.
The index is an instance attribute of the DataFrame, so it can be accessed using the dot notation.
Column names can be accessed in a similar way.

In [5]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
df.columns

Index(['title', 'author', 'price'], dtype='str')

A column Series is selected using square brackets and the column name.
For example:

In [6]:
df["title"]

0             Tangled Web
1                Close Up
2             Foundations
3    Professional Secrets
4               5 Times 5
Name: title, dtype: str

Notice that the row labels are also extracted with the requested column.
To get a single item from the Series, use the square bracket notation and the row label, for example:

In [7]:
df["title"][1]

'Close Up'

A few useful DataFrame methods for inspecting your data:
- ``head()`` shows the first few rows of data. By default, it will show five rows, or you can specify how many.
- ``tail()`` is like ``head()`` but shows the last few rows of data.
- ``describe()`` gives some summary statistics about the numerical columns.
-  ``info()`` returns information such as the column names and their data types.

The ``shape`` of a DataFrame (or Series) is its dimension, the number of rows and columns it has.

In [7]:
df.head(2)

         title       author  price
0  Tangled Web    Eric Mead   40.0
1     Close Up  David Stone   23.1

In [7]:
df.describe()

            price
count    5.000000
mean    92.550000
std    114.489869
min     23.100000
25%     34.650000
50%     40.000000
75%     70.000000
max    295.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   5 non-null      object
 1   author  5 non-null      object
 2   price   5 non-null      float64
dtypes: float64(1), object(2)
memory usage: 248.0+ bytes

In [10]:
df.shape

(5, 3)

## Iterating over DataFrames
A Pandas Series and a Pandas DataFrame are both iterable. That means we can use them in loops. Let's look at a Series first. For the purposes of a loop, a Series can be treated like a list.

In [11]:
title_series = df["title"]

for i in title_series:
    print('The title of this book is {}'.format(i))

The title of this book is Tangled Web
The title of this book is Close Up
The title of this book is Foundations
The title of this book is Professional Secrets
The title of this book is 5 Times 5

Iterating over a DataFrame directly will only give us the column names.

In [11]:
for i in df:
    print(i)

title
author
price

The ``items()`` method allows us to loop through the columns in turn. Each column is provided as a Series, so we can also loop through the data in the column.

In [12]:
for col_name, col_data in df.items():
    print('**New column: {}**'.format(col_name))
    for i in col_data:
        print(i)

**New column: title**
Tangled Web
Close Up
Foundations
Professional Secrets
5 Times 5
**New column: author**
Eric Mead
David Stone
Eberhard Riese
Geoffrey Durham
Richard Kaufman
**New column: price**
40.0
23.1
70.0
295.0
34.65

To iterate through the rows instead of the columns use ``iterrows()``.

In [13]:
for row_name, row_data in df.iterrows():
    print("**New row: {}**".format(row_name))
    for i in row_data:
        print(i)

**New row: 0**
Tangled Web
Eric Mead
40.0
**New row: 1**
Close Up
David Stone
23.1
**New row: 2**
Foundations
Eberhard Riese
70.0
**New row: 3**
Professional Secrets
Geoffrey Durham
295.0
**New row: 4**
5 Times 5
Richard Kaufman
34.65

Another way to iterate through the rows is with ``itertuples()``, which returns a tuple for each row (remember that a tuple is the same as a list except that it can't be modified once it's created).

In [14]:
for row in df.itertuples(name="Book"):
    print(row)

Book(Index=0, title='Tangled Web', author='Eric Mead', price=40.0)
Book(Index=1, title='Close Up', author='David Stone', price=23.1)
Book(Index=2, title='Foundations', author='Eberhard Riese', price=70.0)
Book(Index=3, title='Professional Secrets', author='Geoffrey Durham', price=295.0)
Book(Index=4, title='5 Times 5', author='Richard Kaufman', price=34.65)

Now we can access a piece of data from each row using the column name. It could also be useful as an intermediate step to creating an object from each of the rows in the DataFrame.

In [15]:
for row in df.itertuples(name="Book"):
    print(row.title)

Tangled Web
Close Up
Foundations
Professional Secrets
5 Times 5

## DataFrame selecting

We've already looked at how to select a Series (`df["title"]`), but now we'll get fancy with our selects.

First, you can select any columns you'd like in any order (you can even repeat the columns selected), just pass a list of column titles to the indexing `[]` syntax.
This returns a new DataFrame.
The original DataFrame is not affected.

In [16]:
df[["author", "title"]]

            author                 title
0        Eric Mead           Tangled Web
1      David Stone              Close Up
2   Eberhard Riese           Foundations
3  Geoffrey Durham  Professional Secrets
4  Richard Kaufman             5 Times 5

To select specific rows, use `iloc` with a slicing syntax:

In [11]:
df.iloc[2:-1]

                  title           author  price
2           Foundations   Eberhard Riese   70.0
3  Professional Secrets  Geoffrey Durham  295.0

We can mix them too:

In [12]:
df.iloc[2:-1]["title"]

2             Foundations
3    Professional Secrets
Name: title, dtype: str

Rather than selecting blocks of rows, more often you'll find you'll need to filter them based upon some condition. We do this like so:

In [19]:
df[df["price"] > 50]

                  title           author  price
2           Foundations   Eberhard Riese   70.0
3  Professional Secrets  Geoffrey Durham  295.0

You can use any of the numerical comparators (`== != > >= < <=`). The Series also provides an `isin` function, and a `notna` function. `isin` is a membership check, `notna` filters out `na` values.

In [20]:
df[df["title"].isin(["Foundations", "Close Up"])]

         title          author  price
1     Close Up     David Stone   23.1
2  Foundations  Eberhard Riese   70.0

Note, this is a DataFrame returned, so you can stack further selectors or filters onto it like so:

In [21]:
df[df["price"] > 50]["author"]

2     Eberhard Riese
3    Geoffrey Durham
Name: author, dtype: object

In [22]:
expensive = df[df["price"] > 50]
not_too_expensive = expensive[expensive["price"] < 100]
not_too_expensive

         title          author  price
2  Foundations  Eberhard Riese   70.0

## Exercise 1

### 1a
The next cell contains some information about the 20 highest-grossing movies. 
At the moment, we have a dictionary for each movie showing the rank, title, the money made (in US $), and the year that the film was released. 

In order to create a DataFrame, we need the data in a different format, namely, a dictionary of lists. 

Write some code to create lists for each type of information (ranking, title, etc.) and use these to create the DataFrame. Give the columns the same names as the current dictionary keys. 

Notice that the ranking, worldwide gross and year data are all presented here as strings. These columns should be converted to integers.

In [13]:
movies = [
    {'Ranking': '1', 'Title': 'Avengers: Endgame', 'Worldwide gross ($)': '2797800564', 'Year': '2019'}, 
    {'Ranking': '2', 'Title': 'Avatar', 'Worldwide gross ($)': '2790439000', 'Year': '2009'}, 
    {'Ranking': '3', 'Title': 'Titanic', 'Worldwide gross ($)': '2194439542', 'Year': '1997'},
    {'Ranking': '4', 'Title': 'Star Wars: The Force Awakens', 'Worldwide gross ($)': '2068223624', 'Year': '2015'},
    {'Ranking': '5', 'Title': 'Avengers: Infinity War', 'Worldwide gross ($)': '2048359754', 'Year': '2018'},
    {'Ranking': '6', 'Title': 'Jurassic World', 'Worldwide gross ($)': '1671713208', 'Year': '2015'},
    {'Ranking': '7', 'Title': 'The Lion King', 'Worldwide gross ($)': '1656943394', 'Year': '2019'},
    {'Ranking': '8', 'Title': 'The Avengers', 'Worldwide gross ($)': '1518812988', 'Year': '2012'},
    {'Ranking': '9', 'Title': 'Furious 7', 'Worldwide gross ($)': '1516045911', 'Year': '2015'},
    {'Ranking': '10', 'Title': 'Frozen II', 'Worldwide gross ($)': '1450026933', 'Year': '2019'},
    {'Ranking': '11', 'Title': 'Avengers: Age of Ultron', 'Worldwide gross ($)': '1402805868', 'Year': '2015'},
    {'Ranking': '12', 'Title': 'Black Panther', 'Worldwide gross ($)': '1347280838', 'Year': '2018'},
    {'Ranking': '13', 'Title': 'Harry Potter and the Deathly Hallows – Part 2', 'Worldwide gross ($)': '1342025430', 'Year': '2011'},
    {'Ranking': '14', 'Title': 'Star Wars: The Last Jedi', 'Worldwide gross ($)': '1332539889', 'Year': '2017'},
    {'Ranking': '15', 'Title': 'Jurassic World: Fallen Kingdom', 'Worldwide gross ($)': '1309484461', 'Year': '2018'},
    {'Ranking': '16', 'Title': 'Frozen', 'Worldwide gross ($)': '1290000000', 'Year': '2013'},
    {'Ranking': '17', 'Title': 'Beauty and the Beast', 'Worldwide gross ($)': '1263521126', 'Year': '2017'},
    {'Ranking': '18', 'Title': 'Incredibles 2', 'Worldwide gross ($)': '1242805359', 'Year': '2018'},
    {'Ranking': '19', 'Title': 'The Fate of the Furious', 'Worldwide gross ($)': '1238764765', 'Year': '2017'},
    {'Ranking': '20', 'Title': 'Iron Man 3', 'Worldwide gross ($)': '1214811252', 'Year': '2013'}
]

### 1b
Select the rows for movies from 2017

In [20]:
df = pd.DataFrame(movies)
df[df["Year"] >= "2017"]

   Ranking                           Title Worldwide gross ($)  Year
0        1               Avengers: Endgame          2797800564  2019
4        5          Avengers: Infinity War          2048359754  2018
6        7                   The Lion King          1656943394  2019
9       10                       Frozen II          1450026933  2019
11      12                   Black Panther          1347280838  2018
13      14        Star Wars: The Last Jedi          1332539889  2017
14      15  Jurassic World: Fallen Kingdom          1309484461  2018
16      17            Beauty and the Beast          1263521126  2017
17      18                   Incredibles 2          1242805359  2018
18      19         The Fate of the Furious          1238764765  2017

### 1c
Select the rows which made at least $1,300,000,000 and were released before 2018.

In [24]:
early_year = df[df["Year"] <= "2018"]
early_year[early_year["Worldwide gross ($)"] >= "1300000000"]

,Ranking,Title,Worldwide gross ($),Year
1,2,Avatar,2790439000,2009
2,3,Titanic,2194439542,1997
3,4,Star Wars: The Force Awakens,2068223624,2015
4,5,Avengers: Infinity War,2048359754,2018
5,6,Jurassic World,1671713208,2015
7,8,The Avengers,1518812988,2012
8,9,Furious 7,1516045911,2015
10,11,Avengers: Age of Ultron,1402805868,2015
11,12,Black Panther,1347280838,2018
12,13,Harry Potter and the Deathly Hallows – Part 2,1342025430,2011
13,14,Star Wars: The Last Jedi,1332539889,2017
14,15,Jurassic World: Fallen Kingdom,1309484461,2018

### 1d
Create a new DataFrame by selecting the 'Title' and 'Worldwide gross($)' columns for films released before 2018.

In [46]:
df = pd.DataFrame(movies)
filtered = df[df["Year"] < "2018"]
filtered = filtered[["Title", "Worldwide gross ($)"]]
filtered

                                            Title Worldwide gross ($)
1                                          Avatar          2790439000
2                                         Titanic          2194439542
3                    Star Wars: The Force Awakens          2068223624
5                                  Jurassic World          1671713208
7                                    The Avengers          1518812988
8                                       Furious 7          1516045911
10                        Avengers: Age of Ultron          1402805868
12  Harry Potter and the Deathly Hallows – Part 2          1342025430
13                       Star Wars: The Last Jedi          1332539889
15                                         Frozen          1290000000
16                           Beauty and the Beast          1263521126
18                        The Fate of the Furious          1238764765
19                                     Iron Man 3          1214811252

## Loading, converting and saving data

We've already seen in previous lessons how to load data from a CSV file, and Pandas also provides a set of functions to load data from a CSV file directly into a DataFrame. 

The function `read_csv()` takes the names of a CSV file and creates a DataFrame. This DataFrame will take column names from the CSV file automatically, or you can override this behaviour by setting the optional parameters ``header`` to `0` and ``names`` to a list of the column names you would like to use instead.

If you need to load data from an online source, just replace the file name with the URL of the data. Pandas is smart enough to know what to do.

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv')
df

#URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'raw.githubusercontent.com'. (_ssl.c:1010)>

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Error `URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'raw.githubusercontent.com'. (_ssl.c:1010)>` was due to the cert bit match with raw.githubusercontent.com. Because I'm using proxy in my network to pass the GFW. It has been proved that there won't be such error if a clean network without proxy or VPN.
To workaround this issue(In case anyone anyone in the same network env as me.), use below example instead.
```python
import requests
import pandas as pd
from io import StringIO

url = 'https://raw.githubusercontent.com/pandas-dev/pandas/main/pandas/tests/io/data/csv/tips.csv'
response = requests.get(url, verify=False)
df = pd.read_csv(StringIO(response.text))
df
```

This has downloaded a CSV file from the Pandas GitHub page. 
To save a DataFrame as a CSV use ``to_csv()``. We set ``index=False`` so that the row numbers aren't included in the new file.

In [5]:
df.to_csv("tips.csv", index=False)

But what if you need that data in a completely different format? Well, `Pandas` offers a surprising number of alternative formats. Let's convert it to JSON. If we don't provide a file name to write to, it'll just return the conversion, which is handy for JSON:

In [6]:
df.to_json(orient="records")

'[{"total_bill":16.99,"tip":1.01,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":10.34,"tip":1.66,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":21.01,"tip":3.5,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":23.68,"tip":3.31,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":24.59,"tip":3.61,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":25.29,"tip":4.71,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":8.77,"tip":2.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":26.88,"tip":3.12,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":15.04,"tip":1.96,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":14.78,"tip":3.23,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":10.27,"tip":1.71,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":35.26,"tip":5.0,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":15.42,"tip":1.57,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":18.43,"tip":3.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":14.83,"tip":3.02,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":21.58,"tip":3.92,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":10.33,"tip":1.67,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":16.29,"tip":3.71,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":16.97,"tip":3.5,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":20.65,"tip":3.35,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":17.92,"tip":4.08,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":20.29,"tip":2.75,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":15.77,"tip":2.23,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":39.42,"tip":7.58,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":4},{"total_bill":19.82,"tip":3.18,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":17.81,"tip":2.34,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":4},{"total_bill":13.37,"tip":2.0,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":12.69,"tip":2.0,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":21.7,"tip":4.3,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":19.65,"tip":3.0,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":9.55,"tip":1.45,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":18.35,"tip":2.5,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":4},{"total_bill":15.06,"tip":3.0,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":20.69,"tip":2.45,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":4},{"total_bill":17.78,"tip":3.27,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":24.06,"tip":3.6,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":16.31,"tip":2.0,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":16.93,"tip":3.07,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":18.69,"tip":2.31,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":31.27,"tip":5.0,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":16.04,"tip":2.24,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":17.46,"tip":2.54,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":13.94,"tip":3.06,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":9.68,"tip":1.32,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":30.4,"tip":5.6,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":18.29,"tip":3.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":22.23,"tip":5.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":32.4,"tip":6.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":28.55,"tip":2.05,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":18.04,"tip":3.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":12.54,"tip":2.5,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":10.29,"tip":2.6,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":34.81,"tip":5.2,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":9.94,"tip":1.56,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":25.56,"tip":4.34,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":19.49,"tip":3.51,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":38.01,"tip":3.0,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":4},{"total_bill":26.41,"tip":1.5,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":11.24,"tip":1.76,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":48.27,"tip":6.73,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":4},{"total_bill":20.29,"tip":3.21,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":13.81,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":11.02,"tip":1.98,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":18.29,"tip":3.76,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":4},{"total_bill":17.59,"tip":2.64,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":20.08,"tip":3.15,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":16.45,"tip":2.47,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":3.07,"tip":1.0,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":1},{"total_bill":20.23,"tip":2.01,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":15.01,"tip":2.09,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":12.02,"tip":1.97,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":17.07,"tip":3.0,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":3},{"total_bill":26.86,"tip":3.14,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":25.28,"tip":5.0,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":14.73,"tip":2.2,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":10.51,"tip":1.25,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":17.92,"tip":3.08,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":27.2,"tip":4.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":4},{"total_bill":22.76,"tip":3.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":17.29,"tip":2.71,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":19.44,"tip":3.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":16.66,"tip":3.4,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":10.07,"tip":1.83,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":1},{"total_bill":32.68,"tip":5.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":15.98,"tip":2.03,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":34.83,"tip":5.17,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":4},{"total_bill":13.03,"tip":2.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":18.28,"tip":4.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":24.71,"tip":5.85,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":21.16,"tip":3.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":28.97,"tip":3.0,"sex":"Male","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":22.49,"tip":3.5,"sex":"Male","smoker":"No","day":"Fri","time":"Dinner","size":2},{"total_bill":5.75,"tip":1.0,"sex":"Female","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":16.32,"tip":4.3,"sex":"Female","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":22.75,"tip":3.25,"sex":"Female","smoker":"No","day":"Fri","time":"Dinner","size":2},{"total_bill":40.17,"tip":4.73,"sex":"Male","smoker":"Yes","day":"Fri","time":"Dinner","size":4},{"total_bill":27.28,"tip":4.0,"sex":"Male","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":12.03,"tip":1.5,"sex":"Male","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":21.01,"tip":3.0,"sex":"Male","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":12.46,"tip":1.5,"sex":"Male","smoker":"No","day":"Fri","time":"Dinner","size":2},{"total_bill":11.35,"tip":2.5,"sex":"Female","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":15.38,"tip":3.0,"sex":"Female","smoker":"Yes","day":"Fri","time":"Dinner","size":2},{"total_bill":44.3,"tip":2.5,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":3},{"total_bill":22.42,"tip":3.48,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":20.92,"tip":4.08,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":15.36,"tip":1.64,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":20.49,"tip":4.06,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":25.21,"tip":4.29,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":18.24,"tip":3.76,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":14.31,"tip":4.0,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":14.0,"tip":3.0,"sex":"Male","smoker":"No","day":"Sat","time":"Dinner","size":2},{"total_bill":7.25,"tip":1.0,"sex":"Female","smoker":"No","day":"Sat","time":"Dinner","size":1},{"total_bill":38.07,"tip":4.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":23.95,"tip":2.55,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":25.71,"tip":4.0,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":17.31,"tip":3.5,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":29.93,"tip":5.07,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":10.65,"tip":1.5,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":12.43,"tip":1.8,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":24.08,"tip":2.92,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":4},{"total_bill":11.69,"tip":2.31,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":13.42,"tip":1.68,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":14.26,"tip":2.5,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":15.95,"tip":2.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":12.48,"tip":2.52,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":29.8,"tip":4.2,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":6},{"total_bill":8.52,"tip":1.48,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":14.52,"tip":2.0,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":11.38,"tip":2.0,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":22.82,"tip":2.18,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":3},{"total_bill":19.08,"tip":1.5,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":20.27,"tip":2.83,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":11.17,"tip":1.5,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":12.26,"tip":2.0,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":18.26,"tip":3.25,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":8.51,"tip":1.25,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":10.33,"tip":2.0,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":14.15,"tip":2.0,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":16.0,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":13.16,"tip":2.75,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":17.47,"tip":3.5,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":34.3,"tip":6.7,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":6},{"total_bill":41.19,"tip":5.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":5},{"total_bill":27.05,"tip":5.0,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":6},{"total_bill":16.43,"tip":2.3,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":8.35,"tip":1.5,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":18.64,"tip":1.36,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":3},{"total_bill":11.87,"tip":1.63,"sex":"Female","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":9.78,"tip":1.73,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":7.51,"tip":2.0,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":14.07,"tip":2.5,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":13.13,"tip":2.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":17.26,"tip":2.74,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":24.55,"tip":2.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":19.77,"tip":2.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":29.85,"tip":5.14,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":5},{"total_bill":48.17,"tip":5.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":6},{"total_bill":25.0,"tip":3.75,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":13.39,"tip":2.61,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":16.49,"tip":2.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":21.5,"tip":3.5,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":12.66,"tip":2.5,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":16.21,"tip":2.0,"sex":"Female","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":13.81,"tip":2.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":17.51,"tip":3.0,"sex":"Female","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":24.52,"tip":3.48,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":3},{"total_bill":20.76,"tip":2.24,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":2},{"total_bill":31.71,"tip":4.5,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":4},{"total_bill":10.59,"tip":1.61,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":10.63,"tip":2.0,"sex":"Female","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":50.81,"tip":10.0,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":3},{"total_bill":15.81,"tip":3.16,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":2},{"total_bill":7.25,"tip":5.15,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":31.85,"tip":3.18,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":16.82,"tip":4.0,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":32.9,"tip":3.11,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":17.89,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":14.48,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":9.6,"tip":4.0,"sex":"Female","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":34.63,"tip":3.55,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":34.65,"tip":3.68,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":4},{"total_bill":23.33,"tip":5.65,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":45.35,"tip":3.5,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":3},{"total_bill":23.17,"tip":6.5,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":4},{"total_bill":40.55,"tip":3.0,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":20.69,"tip":5.0,"sex":"Male","smoker":"No","day":"Sun","time":"Dinner","size":5},{"total_bill":20.9,"tip":3.5,"sex":"Female","smoker":"Yes","day":"Sun","time":"Dinner","size":3},{"total_bill":30.46,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":5},{"total_bill":18.15,"tip":3.5,"sex":"Female","smoker":"Yes","day":"Sun","time":"Dinner","size":3},{"total_bill":23.1,"tip":4.0,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":3},{"total_bill":15.69,"tip":1.5,"sex":"Male","smoker":"Yes","day":"Sun","time":"Dinner","size":2},{"total_bill":19.81,"tip":4.19,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":28.44,"tip":2.56,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":15.48,"tip":2.02,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":16.58,"tip":4.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":7.56,"tip":1.44,"sex":"Male","smoker":"No","day":"Thur","time":"Lunch","size":2},{"total_bill":10.34,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":43.11,"tip":5.0,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":4},{"total_bill":13.0,"tip":2.0,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":13.51,"tip":2.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":18.71,"tip":4.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":3},{"total_bill":12.74,"tip":2.01,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":13.0,"tip":2.0,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":16.4,"tip":2.5,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":2},{"total_bill":20.53,"tip":4.0,"sex":"Male","smoker":"Yes","day":"Thur","time":"Lunch","size":4},{"total_bill":16.47,"tip":3.23,"sex":"Female","smoker":"Yes","day":"Thur","time":"Lunch","size":3},{"total_bill":26.59,"tip":3.41,"sex":"Male","smoker":"Yes","day":"Sat","time":"Dinner","size":3},{"total_bill":38.73,"tip":3.0,"sex":"Male","smoker":"

## Exercise 2
To be able to follow this exercise, you will need a CSV file containing data about the passengers aboard the famous Titanic ship on its first and only journey. The data for this exercise is available at [Titanic.csv](https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv)

### 2a
Load the CSV file into a DataFrame called 'titanic'.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv')
df

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                  Heikkinen, Miss Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                          Graham, Miss Margaret Edith
888              Johnston, Miss Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

### 2b 
Inspect the data - view the first 10 rows

In [9]:
df = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv')
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### 2c
Create a DataFrame called 'titanic_age_sex' which only contains the age and sex of the passengers.

### 2d
Get the subset of data which relates to adults (age greater than or equal to 18), call the new DataFrame 'titanic_adults'.
Check how many rows are in this new DataFrame and compare to the original Titanic DataFrame.

## How to find out more

The last thing you need to know is how to discover these functions and how to read their docs so you can read, convert and write many more formats. There are [docs online](https://pandas.pydata.org/pandas-docs/stable/index.html), or you can make use of `dir` and `help` functions, which is handy to know so you can do data science on your Antarctic expedition, or while flying to meet a client, or when you just don't have a good internet connection.

`dir` lists all the methods of a class, `help` shows the documentation.

In [28]:
# list all the methods in pandas that begin with "read_"
list(filter(lambda m: m.startswith("read_"), dir(pd)))

['read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml']

In [29]:
# list all the methods of DataFrame that begin with "to_"
list(filter(lambda m: m.startswith("to_"), dir(df)))

['to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml']

In [30]:
# print the documentation about the read_csv fundtion in pandas
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers.readers:

read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols: 'UsecolsArgType' = None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters: 'Mapping[Hashable, Callable] | None' = None,
    true_values: 'list | None' = None,
    false_values: 'list | None' = None,
    skipinitialspace: 'bool' = False,
    skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool | lib.NoDefault' = <no_default>,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool | lib.NoDefault' = <no_default>,
    date_parser: 'Callable | lib.NoDefault' = <no_default>,
    date_format: 'str | dict[Hashable, str] | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool | lib.NoDefault' = <no_default>,
    low_memory: 'bool' = True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>
) -> 'DataFrame | TextFileReader'
    Read a comma-separated values (csv) file into DataFrame.

    Also supports optionally iterating or breaking of the file
    into chunks.

    Additional help can be found in the online docs for
    `IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
        expected. A local file could be: file://localhost/path/to/table.csv.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method, such as
        a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
    sep : str, default ','
        Character or regex pattern to treat as the delimiter. If ``sep=None``, the
        C engine cannot automatically detect
        the separator, but the Python parsing engine can, meaning the latter will
        be used and automatically detect the separator from only the first valid
        row of the file by Python's builtin sniffer tool, ``csv.Sniffer``.
        In addition, separators longer than 1 character and different from
        ``'\s+'`` will be interpreted as regular expressions and will also force
        the use of the Python parsing engine. Note that regex delimiters are prone
        to ignoring quoted data. Regex example: ``'\r\t'``.
    delimiter : str, optional
        Alias for ``sep``.
    header : int, Sequence of int, 'infer' or None, default 'infer'
        Row number(s) containing column labels and marking the start of the
        data (zero-indexed). Default behavior is to infer the column names: if no ``names``
        are passed the behavior is identical to ``header=0`` and column
        names are inferred from the first line of the file, if column
        names are passed explicitly to ``names`` then the behavior is identical to
        ``header=None``. Explicitly pass ``header=0`` to be able to
        replace existing names. The header can be a list of integers that
        specify row locations for a :class:`~pandas.MultiIndex` on the columns
        e.g. ``[0, 1, 3]``. Intervening rows that are not specified will be
        skipped (e.g. 2 in this example is skipped). Note that this
        parameter ignores commented lines and empty lines if
        ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
        data rather than the first line of the file.
    names : Sequence of Hashable, optional
        Sequence of column labels to apply. If the file contains a header row,
        then you should explicitly pass ``header=0`` to override the column names.
        Duplicates in this list are not allowed.
    index_col : Hashable, Sequence of Hashable or False, optional
      Column(s) to use as row label(s), denoted either by column labels or column
      indices.  If a sequence of labels or indices is given, :class:`~pandas.MultiIndex`
      will be formed for the row labels.

      Note: ``index_col=False`` can be used to force pandas to *not* use the first
      column as the index, e.g., when you have a malformed file with delimiters at
      the end of each line.
    usecols : Sequence of Hashable or Callable, optional
        Subset of columns to select, denoted either by column labels or column indices.
        If list-like, all elements must either
        be positional (i.e. integer indices into the document columns) or strings
        that correspond to column names provided either by the user in ``names`` or
        inferred from the document header row(s). If ``names`` are given, the document
        header row(s) are not taken into account. For example, a valid list-like
        ``usecols`` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
        Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
        To instantiate a :class:`~pandas.DataFrame` from ``data`` with element order
        preserved use ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]``
        for columns in ``['foo', 'bar']`` order or
        ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
        for ``['bar', 'foo']`` order.

        If callable, the callable function will be evaluated against the column
        names, returning names where the callable function evaluates to ``True``. An
        example of a valid callable argument would be ``lambda x: x.upper() in
        ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
        parsing time and lower memory usage.
    dtype : dtype or dict of {Hashable : dtype}, optional
        Data type(s) to apply to either the whole dataset or individual columns.
        E.g., ``{'a': np.float64, 'b': np.int32, 'c': 'Int64'}``
        Use ``str`` or ``object`` together with suitable ``na_values`` settings
        to preserve and not interpret ``dtype``.
        If ``converters`` are specified, they will be applied INSTEAD
        of ``dtype`` conversion.

        .. versionadded:: 1.5.0

            Support for ``defaultdict`` was added. Specify a ``defaultdict`` as input where
            the default determines the ``dtype`` of the columns which are not explicitly
            listed.
    engine : {'c', 'python', 'pyarrow'}, optional
        Parser engine to use. The C and pyarrow engines are faster, while the python engine
        is currently more feature-complete. Multithreading is currently only supported by
        the pyarrow engine.

        .. versionadded:: 1.4.0

            The 'pyarrow' engine was added as an *experimental* engine, and some features
            are unsupported, or may not work correctly, with this engine.
    converters : dict of {Hashable : Callable}, optional
        Functions for converting values in specified columns. Keys can either
        be column labels or column indices.
    true_values : list, optional
        Values to consider as ``True`` in addition to case-insensitive variants of 'True'.
    false_values : list, optional
        Values to consider as ``False`` in addition to case-insensitive variants of 'False'.
    skipinitialspace : bool, default False
        Skip spaces after delimiter.
    skiprows : int, list of int or Callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (``int``)
        at the start of the file.

        If callable, the callable function will be evaluated against the row
        indices, returning ``True`` if the row should be skipped and ``False`` otherwise.
        An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
    skipfooter : int, default 0
        Number of lines at bottom of file to skip (Unsupported with ``engine='c'``).
    nrows : int, optional
        Number of rows of file to read. Useful for reading pieces of large files.
    na_values : Hashable, Iterable of Hashable or dict of {Hashable : Iterable}, optional
        Additional strings to recognize as ``NA``/``NaN``. If ``dict`` passed, specific
        per-column ``NA`` values.  By default the following values are interpreted as
        ``NaN``: " ", "#N/A", "#N/A N/A", "#NA", "-1.#IND", "-1.#QNAN", "-NaN", "-nan",
        "1.#IND", "1.#QNAN", "<NA>", "N/A", "NA", "NULL", "NaN", "None",
        "n/a", "nan", "null ".

    keep_default_na : bool, default True
        Whether or not to include the default ``NaN`` values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is ``True``, and ``na_values`` are specified, ``na_values``
          is appended to the default ``NaN`` values used for parsing.
        * If ``keep_default_na`` is ``True``, and ``na_values`` are not specified, only
          the default ``NaN`` values are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are specified, only
          the ``NaN`` values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is ``False``, and ``na_values`` are not specified, no
          strings will be parsed as ``NaN``.

        Note that if ``na_filter`` is passed in as ``False``, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of ``na_values``). In
        data without any ``NA`` values, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of ``NA`` values placed in non-numeric columns.

        .. deprecated:: 2.2.0
    skip_blank_lines : bool, default True
        If ``True``, skip over blank lines rather than interpreting as ``NaN`` values.
    parse_dates : bool, list of Hashable, list of lists or dict of {Hashable : list}, default False
        The behavior is as follows:

        * ``bool``. If ``True`` -> try parsing the index. Note: Automatically set to
          ``True`` if ``date_format`` or ``date_parser`` arguments have been passed.
        * ``list`` of ``int`` or names. e.g. If ``[1, 2, 3]`` -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of ``list``. e.g.  If ``[[1, 3]]`` -> combine columns 1 and 3 and parse
          as a single date column. Values are joined with a space before parsing.
        * ``dict``, e.g. ``{'foo' : [1, 3]}`` -> parse columns 1, 3 as date and call
          result 'foo'. Values are joined with a space before parsing.

        If a column or index cannot be represented as an array of ``datetime``,
        say because of an unparsable value or a mixture of timezones, the column
        or index will be returned unaltered as an ``object`` data type. For
        non-standard ``datetime`` parsing, use :func:`~pandas.to_datetime` after
        :func:`~pandas.read_csv`.

        Note: A fast-path exists for iso8601-formatted dates.
    infer_datetime_format : bool, default False
        If ``True`` and ``parse_dates`` is enabled, pandas will attempt to infer the
        format of the ``datetime`` strings in the columns, and if it can be inferred,
        switch to a faster method of parsing them. In some cases this can increase
        the parsing speed by 5-10x.

        .. deprecated:: 2.0.0
            A strict version of this argument is now the default, passing it has no effect.

    keep_date_col : bool, default False
        If ``True`` and ``parse_dates`` specifies combining multiple columns then
        keep the original columns.
    date_parser : Callable, optional
        Function to use for converting a sequence of string columns to an array of
        ``datetime`` instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. pandas will try to call ``date_parser`` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by ``parse_dates``) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by ``parse_dates`` into a single array
        and pass that; and 3) call ``date_parser`` once for each row using one or
        more strings (corresponding to the columns defined by ``parse_dates``) as
        arguments.

        .. deprecated:: 2.0.0
           Use ``date_format`` instead, or read in as ``object`` and then apply
           :func:`~pandas.to_datetime` as-needed.
    date_format : str or dict of column -> format, optional
        Format to use for parsing dates when used in conjunction with ``parse_dates``.
        The strftime to parse time, e.g. :const:`"%d/%m/%Y"`. See
        `strftime documentation
        <https://docs.python.org/3/library/datetime.html
        #strftime-and-strptime-behavior>`_ for more information on choices, though
        note that :const:`"%f"` will parse all the way up to nanoseconds.
        You can also pass:

        - "ISO8601", to parse any `ISO8601 <https://en.wikipedia.org/wiki/ISO_8601>`_
            time string (not necessarily in exactly the same format);
        - "mixed", to infer the format for each element individually. This is risky,
            and you should probably use it along with `dayfirst`.

        .. versionadded:: 2.0.0
    dayfirst : bool, default False
        DD/MM format dates, international and European format.
    cache_dates : bool, default True
        If ``True``, use a cache of unique, converted dates to apply the ``datetime``
        conversion. May produce significant speed-up when parsing duplicate
        date strings, especially ones with timezone offsets.

    iterator : bool, default False
        Return ``TextFileReader`` object for iteration or getting chunks with
        ``get_chunk()``.
    chunksize : int, optional
        Number of lines to read from the file per chunk. Passing a value will cause the
        function to return a ``TextFileReader`` object for iteration.
        See the `IO Tools docs
        <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
        for more information on ``iterator`` and ``chunksize``.

    compression : str or dict, default 'infer'
        For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
        Set to ``None`` for no decompression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdDecompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for Zstandard decompression using a
        custom compression dictionary:
        ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

        .. versionchanged:: 1.4.0 Zstandard support.

    thousands : str (length 1), optional
        Character acting as the thousands separator in numerical values.
    decimal : str (length 1), default '.'
        Character to recognize as decimal point (e.g., use ',' for European data).
    lineterminator : str (length 1), optional
        Character used to denote a line break. Only valid with C parser.
    quotechar : str (length 1), optional
        Character used to denote the start and end of a quoted item. Quoted
        items can include the ``delimiter`` and it will be ignored.
    quoting : {0 or csv.QUOTE_MINIMAL, 1 or csv.QUOTE_ALL, 2 or csv.QUOTE_NONNUMERIC, 3 or csv.QUOTE_NONE}, default csv.QUOTE_MINIMAL
        Control field quoting behavior per ``csv.QUOTE_*`` constants. Default is
        ``csv.QUOTE_MINIMAL`` (i.e., 0) which implies that only fields containing special
        characters are quoted (e.g., characters defined in ``quotechar``, ``delimiter``,
        or ``lineterminator``.
    doublequote : bool, default True
       When ``quotechar`` is specified and ``quoting`` is not ``QUOTE_NONE``, indicate
       whether or not to interpret two consecutive ``quotechar`` elements INSIDE a
       field as a single ``quotechar`` element.
    escapechar : str (length 1), optional
        Character used to escape other characters.
    comment : str (length 1), optional
        Character indicating that the remainder of line should not be parsed.
        If found at the beginning
        of a line, the line will be ignored altogether. This parameter must be a
        single character. Like empty lines (as long as ``skip_blank_lines=True``),
        fully commented lines are ignored by the parameter ``header`` but not by
        ``skiprows``. For example, if ``comment='#'``, parsing
        ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in ``'a,b,c'`` being
        treated as the header.
    encoding : str, optional, default 'utf-8'
        Encoding to use for UTF when reading/writing (ex. ``'utf-8'``). `List of Python
        standard encodings
        <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    encoding_errors : str, optional, default 'strict'
        How encoding errors are treated. `List of possible values
        <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

        .. versionadded:: 1.3.0

    dialect : str or csv.Dialect, optional
        If provided, this parameter will override values (default or not) for the
        following parameters: ``delimiter``, ``doublequote``, ``escapechar``,
        ``skipinitialspace``, ``quotechar``, and ``quoting``. If it is necessary to
        override values, a ``ParserWarning`` will be issued. See ``csv.Dialect``
        documentation for more details.
    on_bad_lines : {'error', 'warn', 'skip'} or Callable, default 'error'
        Specifies what to do upon encountering a bad line (a line with too many fields).
        Allowed values are :

        - ``'error'``, raise an Exception when a bad line is encountered.

In [31]:
# print the documentation about the to_csv method of DataFrame
help(df.to_csv)

Help on method to_csv in module pandas.core.generic:

to_csv(
    path_or_buf: 'FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None' = None,
    *,
    sep: 'str' = ',',
    na_rep: 'str' = '',
    float_format: 'str | Callable | None' = None,
    columns: 'Sequence[Hashable] | None' = None,
    header: 'bool_t | list[str]' = True,
    index: 'bool_t' = True,
    index_label: 'IndexLabel | None' = None,
    mode: 'str' = 'w',
    encoding: 'str | None' = None,
    compression: 'CompressionOptions' = 'infer',
    quoting: 'int | None' = None,
    quotechar: 'str' = '"',
    lineterminator: 'str | None' = None,
    chunksize: 'int | None' = None,
    date_format: 'str | None' = None,
    doublequote: 'bool_t' = True,
    escapechar: 'str | None' = None,
    decimal: 'str' = '.',
    errors: 'OpenFileErrors' = 'strict',
    storage_options: 'StorageOptions | None' = None
) -> 'str | None' method of pandas.core.frame.DataFrame instance
    Write object to a comma-separated values (csv) file.

    Parameters
    ----------
    path_or_buf : str, path object, file-like object, or None, default None
        String, path object (implementing os.PathLike[str]), or file-like
        object implementing a write() function. If None, the result is
        returned as a string. If a non-binary file object is passed, it should
        be opened with `newline=''`, disabling universal newlines. If a binary
        file object is passed, `mode` might need to contain a `'b'`.
    sep : str, default ','
        String of length 1. Field delimiter for the output file.
    na_rep : str, default ''
        Missing data representation.
    float_format : str, Callable, default None
        Format string for floating point numbers. If a Callable is given, it takes
        precedence over other numeric formatting parameters, like decimal.
    columns : sequence, optional
        Columns to write.
    header : bool or list of str, default True
        Write out the column names. If a list of strings is given it is
        assumed to be aliases for the column names.
    index : bool, default True
        Write row names (index).
    index_label : str or sequence, or False, default None
        Column label for index column(s) if desired. If None is given, and
        `header` and `index` are True, then the index names are used. A
        sequence should be given if the object uses MultiIndex. If
        False do not print fields for index names. Use index_label=False
        for easier importing in R.
    mode : {'w', 'x', 'a'}, default 'w'
        Forwarded to either `open(mode=)` or `fsspec.open(mode=)` to control
        the file opening. Typical values include:

        - 'w', truncate the file first.
        - 'x', exclusive creation, failing if the file already exists.
        - 'a', append to the end of file if it exists.

    encoding : str, optional
        A string representing the encoding to use in the output file,
        defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
        is a non-binary file object.
    compression : str or dict, default 'infer'
        For on-the-fly compression of the output data. If 'infer' and 'path_or_buf' is
        path-like, then detect compression from the following extensions: '.gz',
        '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
        (otherwise no compression).
        Set to ``None`` for no compression.
        Can also be a dict with key ``'method'`` set
        to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
        other key-value pairs are forwarded to
        ``zipfile.ZipFile``, ``gzip.GzipFile``,
        ``bz2.BZ2File``, ``zstandard.ZstdCompressor``, ``lzma.LZMAFile`` or
        ``tarfile.TarFile``, respectively.
        As an example, the following could be passed for faster compression and to create
        a reproducible gzip archive:
        ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

        .. versionadded:: 1.5.0
            Added support for `.tar` files.

           May be a dict with key 'method' as compression mode
           and other entries as additional compression options if
           compression mode is 'zip'.

           Passing compression options as keys in dict is
           supported for compression modes 'gzip', 'bz2', 'zstd', and 'zip'.
    quoting : optional constant from csv module
        Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
        then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
        will treat them as non-numeric.
    quotechar : str, default '\"'
        String of length 1. Character used to quote fields.
    lineterminator : str, optional
        The newline character or character sequence to use in the output
        file. Defaults to `os.linesep`, which depends on the OS in which
        this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).

        .. versionchanged:: 1.5.0

            Previously was line_terminator, changed for consistency with
            read_csv and the standard library 'csv' module.

    chunksize : int or None
        Rows to write at a time.
    date_format : str, default None
        Format string for datetime objects.
    doublequote : bool, default True
        Control quoting of `quotechar` inside a field.
    escapechar : str, default None
        String of length 1. Character used to escape `sep` and `quotechar`
        when appropriate.
    decimal : str, default '.'
        Character recognized as decimal separator. E.g. use ',' for
        European data.
    errors : str, default 'strict'
        Specifies how encoding and decoding errors are to be handled.
        See the errors argument for :func:`open` for a full list
        of options.

    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    Returns
    -------
    None or str
        If path_or_buf is None, returns the resulting csv format as a
        string. Otherwise returns None.

    See Also
    --------
    read_csv : Load a CSV file into a DataFrame.
    to_excel : Write DataFrame to an Excel file.

    Examples
    --------
    Create 'out.csv' containing 'df' without indices

    >>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
    ...                    'mask': ['red', 'purple'],
    ...                    'weapon': ['sai', 'bo staff']})
    >>> df.to_csv('out.csv', index=False)  # doctest: +SKIP

    Create 'out.zip' containing 'out.csv'

    >>> df.to_csv(index=False)
    'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
    >>> compression_opts = dict(method='zip',
    ...                         archive_name='out.csv')  # doctest: +SKIP
    >>> df.to_csv('out.zip', index=False,
    ...           compression=compression_opts)  # doctest: +SKIP

    To write a csv file to a new folder or nested folder you will first
    need to create it using either Pathlib or os:

    >>> from pathlib import Path  # doctest: +SKIP
    >>> filepath = Path('folder/subfolder/out.csv')  # doctest: +SKIP
    >>> filepath.parent.mkdir(parents=True, exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv(filepath)  # doctest: +SKIP

    >>> import os  # doctest: +SKIP
    >>> os.makedirs('folder/subfolder', exist_ok=True)  # doctest: +SKIP
    >>> df.to_csv('folder/subfolder/out.csv')  # doctest: +SKIP

## Solutions to exercises
## 1
### 1a

In [24]:
movies = [
    {'Ranking': '1', 'Title': 'Avengers: Endgame', 'Worldwide gross ($)': '2797800564', 'Year': '2019'}, 
    {'Ranking': '2', 'Title': 'Avatar', 'Worldwide gross ($)': '2790439000', 'Year': '2009'}, 
    {'Ranking': '3', 'Title': 'Titanic', 'Worldwide gross ($)': '2194439542', 'Year': '1997'},
    {'Ranking': '4', 'Title': 'Star Wars: The Force Awakens', 'Worldwide gross ($)': '2068223624', 'Year': '2015'},
    {'Ranking': '5', 'Title': 'Avengers: Infinity War', 'Worldwide gross ($)': '2048359754', 'Year': '2018'},
    {'Ranking': '6', 'Title': 'Jurassic World', 'Worldwide gross ($)': '1671713208', 'Year': '2015'},
    {'Ranking': '7', 'Title': 'The Lion King', 'Worldwide gross ($)': '1656943394', 'Year': '2019'},
    {'Ranking': '8', 'Title': 'The Avengers', 'Worldwide gross ($)': '1518812988', 'Year': '2012'},
    {'Ranking': '9', 'Title': 'Furious 7', 'Worldwide gross ($)': '1516045911', 'Year': '2015'},
    {'Ranking': '10', 'Title': 'Frozen II', 'Worldwide gross ($)': '1450026933', 'Year': '2019'},
    {'Ranking': '11', 'Title': 'Avengers: Age of Ultron', 'Worldwide gross ($)': '1402805868', 'Year': '2015'},
    {'Ranking': '12', 'Title': 'Black Panther', 'Worldwide gross ($)': '1347280838', 'Year': '2018'},
    {'Ranking': '13', 'Title': 'Harry Potter and the Deathly Hallows – Part 2', 'Worldwide gross ($)': '1342025430', 'Year': '2011'},
    {'Ranking': '14', 'Title': 'Star Wars: The Last Jedi', 'Worldwide gross ($)': '1332539889', 'Year': '2017'},
    {'Ranking': '15', 'Title': 'Jurassic World: Fallen Kingdom', 'Worldwide gross ($)': '1309484461', 'Year': '2018'},
    {'Ranking': '16', 'Title': 'Frozen', 'Worldwide gross ($)': '1290000000', 'Year': '2013'},
    {'Ranking': '17', 'Title': 'Beauty and the Beast', 'Worldwide gross ($)': '1263521126', 'Year': '2017'},
    {'Ranking': '18', 'Title': 'Incredibles 2', 'Worldwide gross ($)': '1242805359', 'Year': '2018'},
    {'Ranking': '19', 'Title': 'The Fate of the Furious', 'Worldwide gross ($)': '1238764765', 'Year': '2017'},
    {'Ranking': '20', 'Title': 'Iron Man 3', 'Worldwide gross ($)': '1214811252', 'Year': '2013'}
]

ranking = [int(m["Ranking"]) for m in movies]
title = [m["Title"] for m in movies]
money = [int(m["Worldwide gross ($)"]) for m in movies]
year = [int(m["Year"]) for m in movies]

df = pd.DataFrame({
    "Ranking": ranking,
    "Title": title,
    "Worldwide gross ($)": money,
    "Year": year
})

df

,Ranking,Title,Worldwide gross ($),Year
0,1,Avengers: Endgame,2797800564,2019
1,2,Avatar,2790439000,2009
2,3,Titanic,2194439542,1997
3,4,Star Wars: The Force Awakens,2068223624,2015
4,5,Avengers: Infinity War,2048359754,2018
5,6,Jurassic World,1671713208,2015
6,7,The Lion King,1656943394,2019
7,8,The Avengers,1518812988,2012
8,9,Furious 7,1516045911,2015
9,10,Frozen II,1450026933,2019
10,11,Avengers: Age of Ultron,1402805868,2015
11,12,Black Panther,1347280838,2018
12,13,Harry Potter and the Deathly Hallows – Part 2,1342025430,2011
13,14,Star Wars: The Last Jedi,1332539889,2017
14,15,Jurassic World: Fallen Kingdom,1309484461,2018
15,16,Frozen,1290000000,2013
16,17,Beauty and the Beast,1263521126,2017
17,18,Incredibles 2,1242805359,2018
18,19,The Fate of the Furious,1238764765,2017
19,20,Iron Man 3,1214811252,2013

### 1b

In [25]:
df[df["Year"]==2017]

    Ranking                     Title  Worldwide gross ($)  Year
13       14  Star Wars: The Last Jedi           1332539889  2017
16       17      Beauty and the Beast           1263521126  2017
18       19   The Fate of the Furious           1238764765  2017

### 1c

In [34]:
df2 = df[df["Worldwide gross ($)"] >= 1300000000]
df2[df2["Year"] < 2018]

,Ranking,Title,Worldwide gross ($),Year
1,2,Avatar,2790439000,2009
2,3,Titanic,2194439542,1997
3,4,Star Wars: The Force Awakens,2068223624,2015
5,6,Jurassic World,1671713208,2015
7,8,The Avengers,1518812988,2012
8,9,Furious 7,1516045911,2015
10,11,Avengers: Age of Ultron,1402805868,2015
12,13,Harry Potter and the Deathly Hallows – Part 2,1342025430,2011
13,14,Star Wars: The Last Jedi,1332539889,2017

### 1d

In [35]:
df3 = df[df["Year"] < 2018][['Title', 'Worldwide gross ($)']]
df3

                                            Title  Worldwide gross ($)
1                                          Avatar           2790439000
2                                         Titanic           2194439542
3                    Star Wars: The Force Awakens           2068223624
5                                  Jurassic World           1671713208
7                                    The Avengers           1518812988
8                                       Furious 7           1516045911
10                        Avengers: Age of Ultron           1402805868
12  Harry Potter and the Deathly Hallows – Part 2           1342025430
13                       Star Wars: The Last Jedi           1332539889
15                                         Frozen           1290000000
16                           Beauty and the Beast           1263521126
18                        The Fate of the Furious           1238764765
19                                     Iron Man 3           1214811252

## 2
### 2a

In [26]:
titanic = pd.read_csv('https://raw.githubusercontent.com/pandas-dev/pandas/main/doc/data/titanic.csv')

### 2b

In [27]:
titanic.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

### 2c

In [38]:
titanic_age_sex = titanic[['Age', 'Sex']]
titanic_age_sex.head()

    Age     Sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

### 2d

In [39]:
titanic_adults = titanic[titanic['Age'] >= 18]

# get the number of records in the new DF and original
titanic.shape , titanic_adults.shape

((891, 12), (601, 12))